apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod-vxlan-100
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "jcnr-nad-bond0",
          "interface":"net1",
          "cni-args": {
            "macVrfVxlanVNI":"100",
            "dataplane":"linux"
          }
        }
      ]
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sleep", "infinity"]
      securityContext: