apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: jcnr-nad-bond0
spec:
  config: '{
    "cniVersion":"0.4.0",
    "name": "cni-bond0",
    "type": "jcnr",
    "args": {
      "macVrfapplyGroups":"evpn-mac-vrf",
      "macVrfName": "bond0",
      "macVrfTarget": "11:11"
    },
    "kubeConfig":"/etc/kubernetes/kubelet.conf"
  }'